#!/bin/bash


echo "email address?"
read email
echo "new password?"
read pwd
sudo mysql<<EOF
UPDATE \`mailserver\`.\`virtual_users\` SET \`password\`=ENCRYPT('$pwd', CONCAT('\$6\$', SUBSTRING(SHA(RAND()), -16))) WHERE \`email\`='$email';
EOF